### PR TITLE
Saving per-feild in the object editor

### PR DESCRIPTION
**Pull request by brittnylapierre**
I've changed the editor to show save/cancel buttons underneath it's fields when they are changed.

If the editor is in create mode, it will still show the save button up top, and  it won't show the members or canvas pages.

The user is redirected to the created manifest or collection once they press save, the editor will be in edit mode, and then they can add members or canvases (once we hook that up again.)

I added the PagedManifest and PagedCollection where they should be.

I added comments for us to know where to hook up the new api code that @SaschaAdler created for us! They look like TODO: ...something about using the new api...

### CODE REVIEW

**Comment by SaschaAdler** [comment]
My merge created conflicts in this, I'm afraid.

**Comment by brittnylapierre** [comment]
@SaschaAdler It's super cool to see your edits in here haha! I pushed a merge

**Comment by SaschaAdler** [comment]
I'm getting a zod error when trying to view collection members:

```
access-admin    | [
access-admin    |   {
access-admin    |     "code": "invalid_type",
access-admin    |     "expected": "array",
access-admin    |     "received": "object",
access-admin    |     "path": [
access-admin    |       "members"
access-admin    |     ],
access-admin    |     "message": "Expected array, received object"
access-admin    |   }
access-admin    | ]
```

Not sure if sorting this out is supposed to be in the scope of this PR, but I figured I'd let you know.

I did change a slug and it seemed to work alright.

**Comment by brittnylapierre** [comment]
@SaschaAdler @DivyaKrishnan26 pushed the fix for the issue you saw above

**Comment by SaschaAdler** [comment]
`EditorActions` and `EditorFrom` log a whole bunch of things to the console. I'm also not seeing either canvases in the manifest editor, or members in the collection editor.

**Comment by brittnylapierre** [comment]
@SaschaAdler I can remove the console logs, but we're going to be adding back the canvas listing and members as @DivyaKrishnan26 hooks up the new infinite scroller

**Comment by brittnylapierre** [comment]
In case you have any suggestions here's the begginging of the member list changing to work with the new paged api:

services/admin/src/lib/components/collections/CollectionContentEditor.svelte

newBatch gets added to the members array as the user scrolls :o

**Pull request closed without merging**
