### PR TITLE
Members context display

### PR DESCRIPTION
**Pull request by DivyaKrishnan26**
The Slug and the Label for Collection members are displayed, The drag and drop works for this. 
My assumptions the logic of the code will change when we work specifically on Pagination part of members

### CODE REVIEW

**Review by RussellMcOrmond — APPROVED** [review]
I looked at the new toggling, and how "Look_up_slugs" stays available.

I notice that it doesn't allow me to actually look-up the second time, even though the button is there.

Ahh, if I hit "Clear Text" first then it works.  I guess something wasn't reset from the earlier lookup and add.

**Comment by DivyaKrishnan26** [comment]
> I looked at the new toggling, and how "Look_up_slugs" stays available.
> 
> I notice that it doesn't allow me to actually look-up the second time, even though the button is there.
> 
> Ahh, if I hit "Clear Text" first then it works. I guess something wasn't reset from the earlier lookup and add.

Can you test now? I was not able to replicate the issue, Although I am making one small change which I feel its a valid one to do, I would want to disable and enable the dd button only when the element is available to add

**Comment by RussellMcOrmond** [comment]
> Can you test now? I was not able to replicate the issue, Although I am making one small change which I feel its a valid one to do, I would want to disable and enable the dd button only when the element is available to add

I think you forgot to push your commit..

**Comment by DivyaKrishnan26** [comment]
I am merging this PR to main, and have anything changed respected to this along with the pagination works.

**Pull request merged**
