### PR TITLE
Adding deleting members

### PR DESCRIPTION
**Pull request by DivyaKrishnan26**
This should have the Drag and drop of members adding member elements and deleting the member elements.

**To Clarify:** I have added the Noid as the new member to the list to Make the link got to the corresponding editor( as I remember we doing the same thing in sapindale). I would want to double confirm on that if we would still be wanting to that or something different in that case.

**Thing to take forward with**: Create the member link to view in the editor for either a Collection/ Manifest.

Note: the Stylings are all kept similar to the Canvas editor.

### CODE REVIEW

**Comment by SaschaAdler** [comment]
I'm having a hard time reviewing this code because I'm running into the same problems with this branch that I ran into with #174. Unfortunately the code that solves this for me is in that branch.

**Comment by DivyaKrishnan26** [comment]
Apologies for making it hard enough, let me know if I can merge the #174 branch into this branch if that might help you.

**Comment by SaschaAdler** [comment]
Not your fault! You could try rebasing this to #174 if you like.

**Comment by DivyaKrishnan26** [comment]
Sure I will try that.

**Comment by SaschaAdler** [comment]
I've merged main (with a few edits). Since we're going in a different direction with lapin on how updates happen, the update code you wrote no longer works. I'll let you know when the new version is ready.

**Pull request merged**
