### PR TITLE
DMDTask schema updates

### LINKED ISSUE #232: `dmdtask` schema updates
See discussion in #230.

---

- Remove references to `store` processes as lapin will take care of that
- Remove the `prefix` field, as the interface will be configured to look up with a prefix after the split.
- Make `id` optional in `SplitRecord`, in case the reason the result isn't valid is that an id couldn't be extracted.

### PR DESCRIPTION
**Pull request by SaschaAdler**
Closes #232.

@brittnylapierre I'm not sure if your code references the schema directly yet; I've changed a few names for things.

I'll be creating some examples of what these should look like in `dmdtask` fixtures.

### CODE REVIEW

**Comment by brittnylapierre** [comment]
@SaschaAdler Yeah! It uses a dmdtask object that is manipulated in the DmdEditor but it's okay if it breaks what I have now, I'll need to edit it based on our plan. If my pr is merged, then this one is merged, I'll create a tiny pr for fixing what i have now to work with the schema changes, then subsequent prs for each step outlined in: https://github.com/crkn-rcdr/Access-Platform/discussions/230 I think! that way I keep things focused and small

**Comment by SaschaAdler** [comment]
I've added some test data that should parse. When we start working on couch/lapin we can test it out as fixtures.

**Review by brittnylapierre — APPROVED** [review]
I like the new schema changes it's easy to understand the states that the split task can be in. Thanks Sascha!

**Review by RussellMcOrmond — COMMENTED** [review]
"    "0.json": jsonAttachment,"

I believe the intention was for this json to be part of items[]?

I like the tests, as it gives me a visual example to confirm I'm understanding what the zod is saying..

**Comment by RussellMcOrmond** [comment]
While adding a note to #227 227 I realised I forgot about labels.  Each metadata format has its own place for labels, which is why it is part of the output.

https://github.com/crkn-rcdr/CIHM-METS-App/blob/64ef1c43697e37815f1fee344bfb4fc5d22c61c4/lib/CIHM/METS/App/Marc.pm#L105-L110


We will want to expand our  ParseRecord to include the label, and to decide what to do with that label.  Current tool just imposes it, so we can start with that and see if staff ever want it optional or editable later.

**Comment by RussellMcOrmond** [comment]
* Up to you for the JSON.  We can keep as an attachment.  I just thought you were thinking of moving it into the ParseRecord in the above.  It becomes a Lapin question if the full record, or only a filtered subset, is sent back to other layers.  This is mostly an optimisation question, ans since these CouchDB documents are ephemeral we can change later if we want without a data migration.

* Label isn't included in the JSON -- the JSON is the parsing of the XML, and the Label is separate.  In the case of the CSV format the label is a separate column (like the ID, which is also not in DC or IssueInfo).

* We should go with the default now, and consider these things as enhancements.  Once staff is actually using the new platform there will be many things that will be more clear than our currently extremely abstract conversations.

**Pull request merged**
