### PR TITLE
Data cleanup

### LINKED ISSUE #379: Fall cleaning: `data`
- [ ] Remove aliases from the spec, for now. We can re-add them when we need to, or come up with an alternative (like an `extraSlugs` array in manifest/collections).
- [ ] Decouple canvases from the access object spec. They are different enough that a lot of code we write has to work around them, for no benefit.
- [ ] Clean up exports; Vite might be able to handle wildcard exports now.
- [ ] Create a new `pdf` type to assist with #384

### PR DESCRIPTION
**Pull request by SaschaAdler**
Closes #379.

- [x] Remove aliases from the spec, for now. We can re-add them when we need to, or come up with an alternative (like an extraSlugs array in manifest/collections).
- [x] Decouple canvases from the access object spec. They are different enough that a lot of code we write has to work around them, for no benefit.
- [x] Create a new pdf type to assist with #384
- [x] `type` view
- [x] making sure nothing breaks in the admin tools

I'll sort out exports, maybe, when we update SvelteKit/Vite.

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
Related to the "pdf" type, I am wondering if you can create a view that would index and count access documents by type?

Output would be similar to: https://admin.canadiana.ca/couchview/access/tree/pdf?group=1&range=false&reduce=true

* skip documents with an _design/ at the beginning of the ID, and those aren't access documents.
* Output "none" if the type field is missing  (we want to notice these, as they aren't valid and shouldn't exist)
* There would then be 3 types at the moment, possibly more in the future.

**Comment by SaschaAdler** [comment]
A couple things:

- I haven't deployed the new view to production yet. Seems to work fine locally.
- I had to change a bunch of types around (primarily) across the repo. Hopefully things are a little cleaner. Editors seem to load alright, but I'm not sure if any other functionality isn't working.
- I removed the "unassign slug" test because it breaks the new data model and therefore fails. I haven't implemented actual deletion of access objects yet. That can probably wait for the next PR.

**Comment by SaschaAdler** [comment]
I'll revert the slug changes. Everything else shouldn't affect anything except for manifests without `canvases` fields.

**Comment by RussellMcOrmond** [comment]
This mango query returns what we would expect, which is the 738 born digital PDF's we will be changing the type of.

```
{
   "selector": {
      "type": "manifest",
      "canvases": {
         "$exists": false
      }
   }
}
```

**Review by RussellMcOrmond — APPROVED** [review]

**Comment by RussellMcOrmond** [comment]
BTW:  This returns no results, also as expected.

```
{
   "selector": {
      "type": "manifest",
      "from": "pdf",
      "canvases": {
         "$exists": true
      }
   }
}
```

**Pull request merged**
