### PR TITLE
Dmd task fixes 

### PR DESCRIPTION
**Pull request by brittnylapierre**
- [x] Can build and run prod and dev
- [x] All three dmd tasks loading correctly (as far as what I can see in the db)
https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc126723a
https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1265540
https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1264a07
- [x] Fixed the success message showing on error
- [x] Send attachment while creating dmd task
- [x] Move lookup/update results to an external store to cleanup components
- [x] Send the lookup request in chunks
- [x] Send the update request in chunks
- [x] Try to make it so the attachments arent sent to the front end when loading the dmdtask
- [x] Edit schema to include file name
- [x] In the table where you have "Valid" you can indicate the "parsed" boolean, as well as message==="" as a boolean.
- [x] The "Preview" button can be where the potentially long "message" field, the XML attachment and the JSON can be shown
- [x] Change select access platform wording + add no prefix option
- [x] Show XML in the preview modal
- [x] Add checkbox to row for selecting items to update
- [x] Add filename into the UI

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
Suggestion...

The "Preview" button can be where the potentially long "message" field, the XML attachment and the JSON can be shown (I like how you did the JSON part).

In the table where you have "Valid" you can indicate the "parsed" boolean, as well as message==="" as a boolean. That way if there is a message, staff will know to look at the "Preview" button to see it.

As you are only showing one at a time, then you don't need to worry about loading any of the XML or JSON in the initial request.  They can be handled in separate requests relating to the specific Preview button pressed.  If the table has less information pushed into it, then then you won't need to paginate and the scroll bar in the browser will be fine for long tables.

**Comment by brittnylapierre** [comment]
Hey @RussellMcOrmond Feel free to check out the UI now - the update (store to swift) method is hooked up for access, so I used the dev environment for testing.

Here's the data I used in dev to test:

Success Task:
{
  "_id": "26efc4882e709f07395c8c577400081c",
  "_rev": "10-d7e0f1b8da00ce52a8487c50951100dc",
  "format": "marc490",
  "user": {
    "name": "Brittny Lapierre",
    "email": "blapierre@crkn.ca"
  },
  "fileName": "MasterFile_Serials.mrc",
  "updated": 1630304092.752,
  "process": {
    "requestDate": 1630252122.896,
    "processDate": 1630304092.752,
    "succeeded": true,
    "message": ""
  },
  "items": [
    {
      "label": "The Quebec directory for ...",
      "parsed": true,
      "output": "marc",
      "message": "",
      "id": "8_06941"
    },
    {
      "label": "Cherrier & Kirwin's Quebec and Levis directory for ...",
      "parsed": true,
      "output": "marc",
      "id": "8_06941_1",
      "message": ""
    },
    {
      "label": "Cherrier's Quebec directory for ...",
      "parsed": true,
      "output": "marc",
      "message": "",
      "id": "8_06941_2"
    }
  ],
  "_attachments": {
    "2.json": {
      "content_type": "application/json",
      "revpos": 9,
      "digest": "md5-gC66f+P6yAYgIyiQmNNQuw==",
      "length": 699,
      "stub": true
    },
    "1.json": {
      "content_type": "application/json",
      "revpos": 8,
      "digest": "md5-gC66f+P6yAYgIyiQmNNQuw==",
      "length": 699,
      "stub": true
    },
    "0.json": {
      "content_type": "application/json",
      "revpos": 7,
      "digest": "md5-EMfBlnetoUElb212i7XL3A==",
      "length": 699,
      "stub": true
    },
    "2.xml": {
      "content_type": "text/xml",
      "revpos": 6,
      "digest": "md5-Wzec+DXj6BHzdlSVhHaocw==",
      "length": 497,
      "stub": true
    },
    "1.xml": {
      "content_type": "text/xml",
      "revpos": 5,
      "digest": "md5-NiN52Tr/UuBSxRhJyBbZvg==",
      "length": 497,
      "stub": true
    },
    "0.xml": {
      "content_type": "text/xml",
      "revpos": 4,
      "digest": "md5-sdKc1TaR2GS3nr9xLZ1MbQ==",
      "length": 497,
      "stub": true
    },
    "metadata": {
      "content_type": "application/octet-stream",
      "revpos": 1,
      "digest": "md5-TtujNLOPhBUBvOxXo5+cTg==",
      "length": 5102086,
      "stub": true
    }
  }
}

I uploaded those attachments using the Fauxton UI:
[xmlAndJsonFiles.zip](https://github.com/crkn-rcdr/Access-Platform/files/7107153/xmlAndJsonFiles.zip)

Waiting Task:
{
  "_id": "26efc4882e709f07395c8c5774009ca7",
  "_rev": "2-78d3cb371d22222b61cec228d0ffdebe",
  "format": "marc490",
  "user": {
    "name": "Brittny Lapierre",
    "email": "blapierre@crkn.ca"
  },
  "fileName": "MasterFile_Serials.mrc",
  "updated": 1630679985.717,
  "process": {
    "requestDate": 1630679985.717
  },
  "_attachments": {
    "metadata": {
      "content_type": "application/octet-stream",
      "revpos": 1,
      "digest": "md5-TtujNLOPhBUBvOxXo5+cTg==",
      "length": 5102086,
      "stub": true
    }
  }
}

Failed Task:
{
  "_id": "26efc4882e709f07395c8c577400600b",
  "_rev": "3-3260995c5dd26f55f602b06367f450af",
  "format": "marc490",
  "user": {
    "name": "Brittny Lapierre",
    "email": "blapierre@crkn.ca"
  },
  "fileName": "MasterFile_Serials.mrc",
  "updated": 1630679150.282,
  "process": {
    "requestDate": 1630252122.896,
    "processDate": 1630304092.752,
    "succeeded": false,
    "message": ""
  },
  "_attachments": {
    "metadata": {
      "content_type": "application/octet-stream",
      "revpos": 1,
      "digest": "md5-TtujNLOPhBUBvOxXo5+cTg==",
      "length": 5102086,
      "stub": true
    }
  }
}

If you spot any issues/want anything improved I can fix them before we merge this into master.

Thanks!

**Comment by RussellMcOrmond** [comment]
I checked out this branch, and did `pnpm prod`

When I go to https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc126723a , it says "No objects were split from the metadata file."

I tried with some others that exist, and they seem to suggest a failure when the report is fine.  Is there something I did wrong in my setting up?  Can you check pointing to the production database and see what results you get?
http://iris.tor.c7a.ca:5984/_utils/index.html#/database/dmdtask/_all_docs


I guessed that the new `filename` field isn't marked optional, and that was causing a problem.  I added a `filename` field to an existing document, and the problem continued.

I am doing `docker-compose logs -f` and see no error output into those logs, or indication what might not be right.


If I try to go to a document that doesn't exist, the tool says "loading" rather than indicating that the job wasn't found.
https://access-dev.canadiana.ca/dmd/somejunk



When I tried a new upload, it would say it uploaded but also "No objects were split from the metadata file."  I checked the relevant CouchDB document and there is no file attachment.
I checked, and there is a change to https://github.com/crkn-rcdr/Access-Platform/pull/275/files#diff-8bdaa0280ba4269595425745e4fd56e122532d6a82c202402ba0d250342cdebb , so this update document will need to be pushed to production before we can confirm that aspect works.



I cleaned things up, did a build and then did `pnpm dev` and then it was able to upload the file to the dev database.

Let me know how you wish to proceed.  If you can check why the reading of existing processed files isn't working as expected, I think the change to the upload will be fine to merge and confirm is working on the production server after the merge.

You will want to make a note about the CouchDB change in BREAKING_CHANGES.md  , which I believe is the current process.

**Comment by brittnylapierre** [comment]
Hey @RussellMcOrmond Can you try the above tests again? You were right on the file name, I made it optional. I had to run the kivik update for prod too, and then I just added better error messaging for the other issues.

Thanks!

**Review by RussellMcOrmond — APPROVED** [review]
I can now see results.  Approving.

Suggestions for this PR, or a later one -- your choice.  You may want to coordinate with Divya and possibly merge some of these and push an update to the demo/production environment.



* When I look at https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1265540

This has a warning message which staff will want to see.  parsed=true can have message="" or message being warnings.

Suggestion to have a "Yes", "No" Under a "Message" column, and only put the message in the Preview.



* Looking at https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc126723a

I thought this was a one-at-a-time lookup, but seems to be a few different bulk lookups.  Does the bulk lookup not have a POST where you give it a larger array to look up?  Using GET is less than ideal (The IDs end up in the logs/etc).

* In https://access-dev.canadiana.ca/dmd/883700ec0baf66fea540b4514afb9304

There are also some messages for a few rows, but not all.  These relate to character encoding of accents (See   N_00485 as an example).

* I see how the message is displayed in https://access-dev.canadiana.ca/dmd/b4586d5dd0630c7ecd68b898214e6789
Having the PReview and the message on the same screen (the preview screen) still easier for staff to diagnose the problem.

Having a table that had valid=No and Message=Yes with a "Preview" would allow them to look in details at both.

**Review by RussellMcOrmond — COMMENTED** [review]
+1

**Comment by brittnylapierre** [comment]
Hey @RussellMcOrmond one last check before I merge this, I improved the message visualisation. (the following are links with tasks in the prod db)

All valid example:
https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1264a07

Parsed = true & message.length > 0 example:
https://access-dev.canadiana.ca/dmd/517ee635a2305bc78b58b9efc1265540

All invalid example:
https://access-dev.canadiana.ca/dmd/b4586d5dd0630c7ecd68b898214e6789

If you think this is good, let me know, and I'll merge it into main. Thanks again!

**Comment by brittnylapierre** [comment]
Just rebased from main

**Comment by RussellMcOrmond** [comment]
Suggestion -- do a merge main rather than a rebase.  The rebased makes is harder to pull/etc, and makes all these commits show up in this PR which aren't part of this PR. (Have to abort a merge I didn't do, delete the local branch, and then checkout the branch...  messy).

Looks good.  Only thing that is missing is the process.message text being displayed somewhere.  In the case of https://access-dev.canadiana.ca/dmd/b4586d5dd0630c7ecd68b898214e6789 it isn't a helpful message (blank spreadsheet columns are unknown headers -- maybe I can trim that in the microservice), but other times it might be useful.  It seems ready enough to push to production and let other staff know to check it out.



Please remember before creating the new image to pull the latest of the image you are building from.  In the case of this Dockerfile it is:  

`docker pull node:16-alpine`

**Comment by brittnylapierre** [comment]
Screenshot from 2021-09-07 14-25-29

Sounds good & will do! I added the process.message using a status notification below the file name.

**Pull request merged**
