### PR TITLE
Docker production images

### LINKED ISSUE #66: Orchestrate the use of a Kivik instance throughout the repo for development
The current instructions involve some manual steps.  There is a REST API we can talk to in order to automate the setup if we wished.

Is there interest, or is the documentation of a few manual steps for developers sufficient for now?

https://docs.couchdb.org/en/latest/api/server/configuration.html

### LINKED ISSUE #86: Production Docker image for the admin tools
Keeping track of workspace dependencies locally means that Docker images can't be built just by copying some files in a particular service's directory. A more comprehensive solution is required.

### PR DESCRIPTION
**Pull request by SaschaAdler**
- [x] environment variable all the things
- [x] ensure dev build works with haproxy ssl and local hosts
- [x] production image (can run lapin/admin)
- [x] ensure auth works

I'll document things in a subsequent PR.

Closes #66. Closes #86.

### CODE REVIEW

**Comment by SaschaAdler** [comment]
I can do this in multiple PRs if it ends up taking a while and some of this needs to be merged asap.

**Comment by SaschaAdler** [comment]
In case anyone wants to experiment with this now: It currently works under the assumption that you're visiting the dev admin tools at https://access-dev.canadiana.ca and not http://localhost:4747. You'll need to add `access-dev.canadiana.ca` to `/etc/hosts`. This will all be documented properly at some point.

**Comment by SaschaAdler** [comment]
Some more config to point out:

1. I dropped the `docker` from the package.json scripts.
2. You'll need to copy `env.secret.example` to `env.secret` and fetch the values from our shared 1password vault.

**Comment by RussellMcOrmond** [comment]
Q: Conceptually, if someone is working on Sapindale they would run the haproxy from this as part of their testing?

**Comment by SaschaAdler** [comment]
> Q: Conceptually, if someone is working on Sapindale they would run the haproxy from this as part of their testing?

Yeah. Same with cap.

**Pull request merged**
