### PR TITLE
Test data for Cantaloupe handling the `extension` field for canvases.

### PR DESCRIPTION
**Pull request by RussellMcOrmond**
See: https://github.com/crkn-rcdr/Access-Platform/issues/137

### CODE REVIEW

**Comment by RussellMcOrmond** [comment]
TODO:

* Make copies of images to `access-files` container
* Update fixtures to add `extension` sub-field, and remove `path` sub-field from `master` field

**Comment by RussellMcOrmond** [comment]
Before I move forward I'd like a second pair of eyes to confirm what is in the fixture here is what we intend.

I've also copied files into the access-files container based on the fixtures.


```
copy oocihm.45116/data/sip/data/files/oocihm.45116.0002.tif in preservation-cihm-aip to 69429/c02r3nx9kj8p.tif in access-files
copy oocihm.8_06941_1/data/sip/data/files/0002.jpg in preservation-cihm-aip to 69429/c0610vs1v70v.jpg in access-files
copy oocihm.8_06941_2/data/sip/data/files/0002.jpg in preservation-cihm-aip to 69429/c0513tw3hp7p.jpg in access-files
copy oocihm.45116/data/sip/data/files/oocihm.45116.0001.tif in preservation-cihm-aip to 69429/c06d5pb4d58z.tif in access-files
copy oocihm.8_06941_2/data/sip/data/files/0003.jpg in preservation-cihm-aip to 69429/c0183435vx78.jpg in access-files
copy oocihm.8_06941_2/data/sip/data/files/0001.jpg in preservation-cihm-aip to 69429/c08s4jp15g01.jpg in access-files
copy oocihm.8_06941_1/data/sip/data/files/0003.jpg in preservation-cihm-aip to 69429/c02805046f82.jpg in access-files
copy oocihm.8_06941_1/data/sip/data/files/0001.jpg in preservation-cihm-aip to 69429/c09s1kj9h004.jpg in access-files
copy oocihm.8_06941_2/data/sip/data/files/0008.jpg in preservation-cihm-aip to 69429/c0cj87k0gq3s.jpg in access-files
copy oocihm.8_06941_2/data/sip/data/files/0007.jpg in preservation-cihm-aip to 69429/c0h98zb84g4k.jpg in access-files
copy oocihm.8_06941_1/data/sip/data/files/0007.jpg in preservation-cihm-aip to 69429/c0j678v3mt8m.jpg in access-files
copy oocihm.45116/data/sip/data/files/oocihm.45116.0006.tif in preservation-cihm-aip to 69429/c0jq0ss90z39.tif in access-files
copy oocihm.8_06941_1/data/sip/data/files/0008.jpg in preservation-cihm-aip to 69429/c0dj58f8t71q.jpg in access-files
copy oocihm.45116/data/sip/data/files/oocihm.45116.0007.tif in preservation-cihm-aip to 69429/c0dz0311c62f.tif in access-files
copy oocihm.8_06941_1/data/sip/data/files/0006.jpg in preservation-cihm-aip to 69429/c0nz80n18k93.jpg in access-files
copy oocihm.8_06941_2/data/sip/data/files/0006.jpg in preservation-cihm-aip to 69429/c0n00zr2z33x.jpg in access-files
copy oocihm.45116/data/sip/data/files/oocihm.45116.0005.tif in preservation-cihm-aip to 69429/c0pg1hk6nq31.tif in access-files
copy oocihm.8_06941_2/data/sip/data/files/0004.jpg in preservation-cihm-aip to 69429/c0wh2d987m77.jpg in access-files
copy oocihm.8_06941_2/data/sip/data/files/0005.jpg in preservation-cihm-aip to 69429/c0rr1pj0kv4w.jpg in access-files
copy oocihm.45116/data/sip/data/files/oocihm.45116.0004.tif in preservation-cihm-aip to 69429/c0t727c49g60.tif in access-files
copy oocihm.8_06941_1/data/sip/data/files/0004.jpg in preservation-cihm-aip to 69429/c0xg9f66k47d.jpg in access-files
copy oocihm.8_06941_1/data/sip/data/files/0005.jpg in preservation-cihm-aip to 69429/c0sq8qd8xc3v.jpg in access-files
copy oocihm.45116/data/sip/data/files/oocihm.45116.0003.tif in preservation-cihm-aip to 69429/c0z02z51z77x.tif in access-files
```

**Comment by SaschaAdler** [comment]
I added a missing comma to one of the new fixtures. The files look good otherwise.

Note that if anyone runs the updateFixtures script, I believe that these will be overwritten. After the production database is migrated we can add any important fixtures to the script.

**Review by SaschaAdler — APPROVED** [review]

**Comment by RussellMcOrmond** [comment]
I hope that #137 and #135 are completed soon, and that when someone runs `updateFigures` next it will be with references to the access-files images.

**Pull request merged**
