### PR TITLE
Back-end hookups for saving objects

### PR DESCRIPTION
**Pull request by brittnylapierre**
To be included in this pull request:

- [x] Improvements made to the validator of noid.resolveMany 
- [x] Save route added with validation
- [x]  Confirmation status animations added for back end save request (note for B - make some sort of service were backend calls can hook into optionally as the developer writes them to show result status information)
- [x] Validation checks as the user edits objects in the editor
- [x] Save button disabled if the object is in an invalid state

### CODE REVIEW

**Comment by SaschaAdler** [comment]
The comment you may have heard me mention that I have in the meeting is:

The lapin methods for accepting edits to manifests/collections probably shouldn't expect entire Manifest/Collection objects, since many of those fields aren't going to be editable by staff. I set up `EditableManifest` and `EditableCollection` as types/parsers to handle this sort of thing.

We could then implement Couch update functions for inserting the updated editable fields into existing records, which means we won't have to worry about Couch revision control management.

A `save` mutation could have input that looks like

```json
{
  "id": "69429/...",
  "type": "manifest",
  "update": {
    "slug": "..."
    "label": { ... }
    "canvases": [ ... ]
  }
}
```

might be easier to validate in lapin.

**Comment by brittnylapierre** [comment]
> The comment you may have heard me mention that I have in the meeting is:
> 
> The lapin methods for accepting edits to manifests/collections probably shouldn't expect entire Manifest/Collection objects, since many of those fields aren't going to be editable by staff. I set up `EditableManifest` and `EditableCollection` as types/parsers to handle this sort of thing.
> 
> We could then implement Couch update functions for inserting the updated editable fields into existing records, which means we won't have to worry about Couch revision control management.
> 
> A `save` mutation could have input that looks like
> 
> ```js
> {
>   "id": "69429/...",
>   "type": "manifest",
>   "update": {
>     "slug": "...",
>     "label": { ... },
>     "canvases": [ ... ]
>   }
> }
> ```
> 
> might be easier to validate in lapin.

So much easier! I'll edit my code to work with this object type I'm not sure how I forgot, sorry

**Comment by DivyaKrishnan26** [comment]
> The comment you may have heard me mention that I have in the meeting is:
> 
> The lapin methods for accepting edits to manifests/collections probably shouldn't expect entire Manifest/Collection objects, since many of those fields aren't going to be editable by staff. I set up `EditableManifest` and `EditableCollection` as types/parsers to handle this sort of thing.
> 
> We could then implement Couch update functions for inserting the updated editable fields into existing records, which means we won't have to worry about Couch revision control management.
> 
> A `save` mutation could have input that looks like
> 
> ```js
> {
>   "id": "69429/...",
>   "type": "manifest",
>   "update": {
>     "slug": "...",
>     "label": { ... },
>     "canvases": [ ... ]
>   }
> }
> ```
> 
> might be easier to validate in lapin.

Lapin was set up earlier with this idea right? Having to update only the EditableObjects and not the entire Collection/Object.

**Comment by brittnylapierre** [comment]
For not

> > The comment you may have heard me mention that I have in the meeting is:
> > The lapin methods for accepting edits to manifests/collections probably shouldn't expect entire Manifest/Collection objects, since many of those fields aren't going to be editable by staff. I set up `EditableManifest` and `EditableCollection` as types/parsers to handle this sort of thing.
> > We could then implement Couch update functions for inserting the updated editable fields into existing records, which means we won't have to worry about Couch revision control management.
> > A `save` mutation could have input that looks like
> > ```js
> > {
> >   "id": "69429/...",
> >   "type": "manifest",
> >   "update": {
> >     "slug": "...",
> >     "label": { ... },
> >     "canvases": [ ... ]
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > might be easier to validate in lapin.
> 
> Lapin was set up earlier with this idea right? Having to update only the EditableObjects and not the entire Collection/Object.

The data package had them set up but I've been writing (probably temporary or first draft) lapin routes for us. I forgot to use the Editable versions in my initial validator method so I edited it today!

**Comment by brittnylapierre** [comment]
Okay I think this can be reviewed/tested. I used chrome today for all of this so tomorrow I'll go on FF to make sure everything looks good there.

- when you edit an existing collection or manifest or create a new one, if the property value you enter is incorrect, you will see a notification bar close to the input associated with the property. For now for the canvases, it's one notification bar over-top of the thumbnail list, canvas viewer, and canvas label editor. 
- If anything is invalid, the save button will be hidden
- when save your changes, you will get a 'changes saved!' green confirmation at the bottom right corner or the screen (We put a lot of actions to the top right so I don't want to cover those) This will stay for aprox. 10 seconds before vanishing. 
- if the backend call errors, you'll see a fail notification. this will not be cleared until the user presses dismiss
- when you click the info button on these notifications, you can see what the server passed back (good for debugging for us in the future, we can ask people to copy it into a support ticket)
- you can attach the notifications to any backend call, I'll write up how to do it
- notifications will be staggered in the ui so they won't overlap (could be made fancier)
- if you press save on a new object it will quietly redirect you to the edit page for the object (you'll see the noid not the /new in the route)

Play around and let me know anything that needs to be changed and if you can break this functionality.

I will need to figure out how/where will be best to add the calls to the noid service for generating new noids too. (https://github.com/crkn-rcdr/Access-Platform/issues/191)

**Comment by SaschaAdler** [comment]
@brittnylapierre I'm not sure if you're working on replacing the CouchDB inserts with update functions in this branch, but I hope we can merge this into `main` as soon as possible since it solves problems I'm having with lapin and the admin tools in other PRs. Let me know how I can help.

**Comment by brittnylapierre** [comment]
@SaschaAdler Hey sorry, I'm stuck on a vite error after pulling the latest changes from main and deleteing node_modules and restarting the services hasn't been working for me:

500: The requested module '/@id/__vite-browser-external:http' does not provide an export named 'Agent' 

I have a updater function set up per each property, and was wondering what kind of validation should go in the updater function vs the lapin router input test?

I also wanted to know if you wanted me to make one router and edit route per property, or if i should make a general edit route in lapin router that calls the right update functions for any properties passed in?

I'm not sure if it will help but I'll try cloning fresh to see if the error goes away, but I'll be changing what I've done so far once i can test it and based on your suggestions from my questions!

I'll be working late today because of an appointment, so I can aim for this all to be fixed tomorrow morning, sorry for the delay!

**Comment by SaschaAdler** [comment]
I don't know that each property needs its own update function. I was thinking that there should be `editManifest` and `editCollection` update functions that process save requests from the admin tools. We could validate these a few ways, but based on what I'm suggesting in #200 I think we should have the access database handler provide e.g. an `editManifest` method, which accepts an id and an `EditableManifest` object as arguments, validates the `EditableManifest` object with its schema, and then calls the update function.

The routes should be separated by type, also, and it might make sense to create `manifest` and `collection` routers in `lapin-router`, to go along with `object`. Also, `routes/noid` can be merged with `routes/object`.

**Comment by brittnylapierre** [comment]
> I don't know that each property needs its own update function. I was thinking that there should be `editManifest` and `editCollection` update functions that process save requests from the admin tools. We could validate these a few ways, but based on what I'm suggesting in #200 I think we should have the access database handler provide e.g. an `editManifest` method, which accepts an id and an `EditableManifest` object as arguments, validates the `EditableManifest` object with its schema, and then calls the update function.
> 
> The routes should be separated by type, also, and it might make sense to create `manifest` and `collection` routers in `lapin-router`, to go along with `object`. Also, `routes/noid` can be merged with `routes/object`.

Awesome okay this plan makes a lot of sense to me thanks! I'm hoping the fresh pull fixes the weird vite issue I'm having (commenting out my editor component doesn't resolve it and I see the admin app logging the response so I do think it's some weird merge caching thing going on from what I can tell)

**Comment by SaschaAdler** [comment]
I've created an issue for the discussion in #200 (#202) and I'll work on that now; I'll let you know when it's merged into `main`.

**Pull request merged**
